Fixes wss sessionHandler()
Loading the page in the browser threw:
TypeError: Cannot read property 'session' of undefined
from node_modules/express-session/index.js:181
As per https://github.com/websockets/ws/issues/1114
ws after 3.0.0 no longer has ws.upgradeReq.
Workaround is to use the request object provided by the
callback of the ws.on('connection')
Also removes cookie-parser which is no longer needed
for this version of express-session.